/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prova;

import javax.swing.JOptionPane;


public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Grupo = new javax.swing.JButton();
        text_Nome = new javax.swing.JTextField();
        text_Idade = new javax.swing.JTextField();
        text_Sexo = new javax.swing.JTextField();
        cadastrar = new javax.swing.JButton();
        listaIdoso = new javax.swing.JButton();
        listaCrianca = new javax.swing.JButton();
        listaAdulto = new javax.swing.JButton();
        registrados = new javax.swing.JButton();
        ordernados = new javax.swing.JButton();
        Atender = new javax.swing.JButton();
        visor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        jLabel1.setText("Sexo do Candidato (F ou M):");

        jLabel2.setText("Idade do Candidato:");

        jLabel3.setText("Nome do Candidato:");

        Grupo.setBackground(new java.awt.Color(240, 105, 136));
        Grupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/coffee_.png"))); // NOI18N
        Grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrupoActionPerformed(evt);
            }
        });

        cadastrar.setText("Cadastrar");
        cadastrar.setPreferredSize(new java.awt.Dimension(89, 25));
        cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarMouseClicked(evt);
            }
        });
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        listaIdoso.setText("Lista a fila de idosos");
        listaIdoso.setMaximumSize(new java.awt.Dimension(150, 25));
        listaIdoso.setMinimumSize(new java.awt.Dimension(150, 25));
        listaIdoso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaIdosoActionPerformed(evt);
            }
        });

        listaCrianca.setText("Lista a fila de Criança");
        listaCrianca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaCriancaActionPerformed(evt);
            }
        });

        listaAdulto.setText("Lista a fila de adultos");
        listaAdulto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaAdultoActionPerformed(evt);
            }
        });

        registrados.setText("Todos os candidatos  registrados");
        registrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registradosActionPerformed(evt);
            }
        });

        ordernados.setText("Todos os candidatos  ordenados");
        ordernados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordernadosActionPerformed(evt);
            }
        });

        Atender.setText("Atender");
        Atender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(text_Idade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(listaIdoso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Atender))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(visor, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(listaCrianca)
                                .addGap(18, 18, 18)
                                .addComponent(listaAdulto)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ordernados)
                                    .addComponent(registrados))))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Grupo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text_Idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(text_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(listaIdoso, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listaCrianca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listaAdulto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(visor, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(Atender, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(registrados, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ordernados, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrupoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Ismael Macedo_RGM:2341818-4"
                + "\nThomas Navarro_RGM:23206942 ");
    }//GEN-LAST:event_GrupoActionPerformed

    Pessoa p = new Pessoa();
    Pessoa2 p2 = new Pessoa2();
    
    QueueAdulto qAdulto = new QueueAdulto();
    QueueCriancas qCriancas = new QueueCriancas();
    QueueIdoso qIdoso = new QueueIdoso();
    QueueRegistrados qRegistrados = new QueueRegistrados();
    int cont = 0;
    
    
    String vetor [] = new String[cont+1];

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        // TODO add your handling code here:
        cont++;
       String nome = text_Nome.getText();
        String sexo = text_Sexo.getText();
        int idade = Integer.parseInt(text_Idade.getText());
        String idade2 = text_Idade.getText();

        p.setNome_Candidato(nome);
        p.setSexo(sexo);
        p.setIdade_Candidato(idade);
        
        p2.setNome_Candidato(nome);
        p2.setSexo(sexo);
        p2.setIdade_Candidato(idade2);

        if (p.getIdade_Candidato() < 15) {
            qCriancas.enqueue(p.toString());
        } else if (p.getIdade_Candidato() >= 15 && p.getIdade_Candidato() < 59) {
            qAdulto.enqueue(p.toString());
        } else {
            qIdoso.enqueue(p.toString());
        }
        
        qRegistrados.enqueue(p.toString());
        vetor[cont] = p2.toString();
        
        text_Nome.setText("");
        text_Idade.setText("");
        text_Sexo.setText("");
    }//GEN-LAST:event_cadastrarActionPerformed

    private void AtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtenderActionPerformed
        // TODO add your handling code here:
        if (!qRegistrados.isEmpty()) {
            if (!qIdoso.isEmpty()) {
                visor.setText((String) qIdoso.dequeue());
            } else if (!qCriancas.isEmpty()) {
                visor.setText((String) qCriancas.dequeue());
            } else if (!qAdulto.isEmpty()) {
                visor.setText((String) qAdulto.dequeue());
            }
        } else if (qRegistrados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sem Pacientes\nNo momento");
        }
    }//GEN-LAST:event_AtenderActionPerformed

    private void registradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registradosActionPerformed
        // TODO add your handling code here:
                visor.setText(qRegistrados.toString());
    }//GEN-LAST:event_registradosActionPerformed

    private void listaIdosoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaIdosoActionPerformed
        // TODO add your handling code here:
      visor.setText(qIdoso.toString());
        
    }//GEN-LAST:event_listaIdosoActionPerformed

    private void cadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarMouseClicked

    private void listaCriancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaCriancaActionPerformed
        // TODO add your handling code here:
                visor.setText(qCriancas.toString());
    }//GEN-LAST:event_listaCriancaActionPerformed

    private void listaAdultoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaAdultoActionPerformed
        // TODO add your handling code here:
                visor.setText(qAdulto.toString());
    }//GEN-LAST:event_listaAdultoActionPerformed

    private void ordernadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordernadosActionPerformed
        // TODO add your handling code here:
        String aux = "";
        for (int i = 0; i < vetor.length; i++)
            {
                for (int j = 0; j < vetor.length; j++)
                {
                    if (vetor[i].compareToIgnoreCase(vetor[j]) > 0)
                    {
    //aqui acontece a troca, do maior cara  vaia para a direita e o menor para a esquerda
                        aux = vetor[i];
                        vetor[i] = vetor[j];
                        vetor[j] = aux;
                    }
                }
            }
    }//GEN-LAST:event_ordernadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atender;
    private javax.swing.JButton Grupo;
    private javax.swing.JButton cadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton listaAdulto;
    private javax.swing.JButton listaCrianca;
    private javax.swing.JButton listaIdoso;
    private javax.swing.JButton ordernados;
    private javax.swing.JButton registrados;
    private javax.swing.JTextField text_Idade;
    private javax.swing.JTextField text_Nome;
    private javax.swing.JTextField text_Sexo;
    private javax.swing.JTextField visor;
    // End of variables declaration//GEN-END:variables
}
